# Generated by Django 2.2.16 on 2023-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230111_1142'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='user_author_unique'),
        ),
    ]
